version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Setting the root password
      MYSQL_DATABASE: fideli     # Optional: Specify a default database
    ports:
      - "3306:3306"              # Exposing MySQL port 3306 to the host

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql            # Linking phpMyAdmin to MySQL service
      MYSQL_ROOT_PASSWORD: root  # Using the root password to access MySQL
    ports:
      - "8080:80"                # Exposing phpMyAdmin on port 8080

networks:
  default:
    driver: bridge
